# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: mrvautin
google_analytics: UA-7038832-3
title: mrvautin

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: mrvautin

description: Stylish Jekyll Theme
author:
  name: mrvautin
  email: hi@markmoffat.com
  github: mrvautin
  twitter: mrvautin

rss_path: feed.xml

BASE_PATH: https://mrvautin.com
url: mrvautin.com

plugins:
  - jekyll-paginate
  - jekyll-sitemap
